### ISSUE TITLE
vector-binary-instances 0.2.3.0 reverses element order on decode

### ISSUE THREAD

**Issue by snoyberg** [bos/vector-binary-instances#6]
Pinging @bgamari, who made the upload to Hackage. I don't see the code changes in this repo.

Here's a simple program to demonstrate the problem:

```haskell
#!/usr/bin/env stack
-- stack runghc --resolver lts-5.7 --package vector-binary-instances

import qualified Data.Vector.Unboxed as V
import Data.Vector.Binary ()
import Data.Binary (encode, decode)

main :: IO ()
main = do
    let v = V.enumFromTo 0 9 :: V.Vector Int
    print v
    print $ (decode $ encode v :: V.Vector Int)
```

If you run this with vector-binary-instances 0.2.3.0, you get the output:

```
[0,1,2,3,4,5,6,7,8,9]
[9,8,7,6,5,4,3,2,1,0]
```

Running with vector-binary-instances 0.2.1.1 (in LTS-5.6) gives the expected output:

```
[0,1,2,3,4,5,6,7,8,9]
[0,1,2,3,4,5,6,7,8,9]
```

This is a serious bug, and seemingly can be resolved by uploading the current version of master to Hackage.

**Comment by bgamari** [comment]
Oh dear, what a mess. I am very sorry about this. This release appears to be generally a disaster,

 * Due to inverting the remote names in my local working tree the released code was never pushed to `bos`'s repository
 * The release itself was apparently insufficiently and does indeed invert the order of the decoded output.

I have pushed a new release (which now includes a simple testsuite) to Hackage and have marked 0.2.3.0 as deprecated.

@snoyberg, thank you for reporting this and my apologies for any time this may have cost you.

**Comment by snoyberg** [comment]
Wow, thanks for the really rapid response @bgamari! It didn't cause me too much trouble, I was just really surprised when the Travis tests for https://github.com/fpco/serial-bench started to fail.
